(add-to-list 'load-path "~/.emacs.d/core/modules")

(require 'beacon-config)
(require 'exec-path-from-shell-config)
(require 'kpm-list-config)
(require 'magit-config)
(require 'minimal-fringes-config)
(require 'multi-term-config)
;;(require 'powerline-config)
(require 'swiper-config)
(require 'undo-tree-config)
(require 'uniquify-config)
(require 'vlf-config)
(require 'zoom-config)
(require 'elfeed-config)

(provide 'core-modules)
